ALTER TYPE "AIActionProposalType" ADD VALUE 'CREATE_RESERVATION';
ALTER TYPE "AIActionProposalType" ADD VALUE 'UPDATE_RESERVATION';
ALTER TYPE "AIActionProposalType" ADD VALUE 'TRANSITION_RESERVATION_STATUS';
