ALTER TYPE "AIActionProposalType" ADD VALUE 'CREATE_MENU_ITEM';
ALTER TYPE "AIActionProposalType" ADD VALUE 'UPDATE_MENU_ITEM';
ALTER TYPE "AIActionProposalType" ADD VALUE 'SET_MENU_ITEM_AVAILABILITY';
ALTER TYPE "AIActionProposalType" ADD VALUE 'ADD_RECIPE_INGREDIENT';
ALTER TYPE "AIActionProposalType" ADD VALUE 'UPDATE_RECIPE_INGREDIENT';
ALTER TYPE "AIActionProposalType" ADD VALUE 'REMOVE_RECIPE_INGREDIENT';

ALTER TABLE "AIActionProposal" ADD COLUMN "executedResourceId" TEXT;
