"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { ActionFeedback } from "@/components/catalog/action-feedback";
import type { CatalogActionState } from "@/lib/catalog/action-utils";
import { createPurchaseOrderAction, deletePurchaseOrderAction, transitionPurchaseOrderAction, updatePurchaseOrderAction } from "@/lib/purchase-orders/actions";
import type { PurchaseOrderStatusValue } from "@/lib/purchase-orders/policy";

type SupplierOption = { id: string; name: string };
type IngredientOption = { id: string; name: string; unit: string; costPerUnit: number };
type Line = { ingredientId: string; quantity: string; unitCost: string };
type PurchaseOrderView = { id: string; supplier: SupplierOption; status: PurchaseOrderStatusValue; totalAmount: number; orderedAt: string | null; expectedAt: string | null; createdAt: string; items: Array<{ id: string; ingredientId: string; ingredientName: string; unit: string; quantity: number; unitCost: number }> };
const initialState: CatalogActionState = { status: "idle" };
const inputClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/10";

function OrderForm({ suppliers, ingredients, order }: { suppliers: SupplierOption[]; ingredients: IngredientOption[]; order?: PurchaseOrderView }) {
  const handler = order ? updatePurchaseOrderAction : createPurchaseOrderAction;
  const [state, action, pending] = useActionState(handler, initialState);
  const [lines, setLines] = useState<Line[]>(order?.items.map((item) => ({ ingredientId: item.ingredientId, quantity: String(item.quantity), unitCost: String(item.unitCost) })) ?? [{ ingredientId: "", quantity: "", unitCost: "" }]);
  const updateLine = (index: number, change: Partial<Line>) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...change } : line));
  const chooseIngredient = (index: number, ingredientId: string) => { const ingredient = ingredients.find((item) => item.id === ingredientId); updateLine(index, { ingredientId, unitCost: ingredient ? String(ingredient.costPerUnit) : "" }); };
  return <form action={action} className="mt-5 space-y-4">
    {order && <input type="hidden" name="purchaseOrderId" value={order.id} />}
    <input type="hidden" name="items" value={JSON.stringify(lines)} />
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="text-xs font-semibold text-slate-600">Supplier</label><select name="supplierId" required defaultValue={order?.supplier.id ?? ""} className={`${inputClass} mt-1`}><option value="" disabled>Select supplier</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></div><div><label className="text-xs font-semibold text-slate-600">Expected date <span className="font-normal text-slate-400">optional</span></label><input name="expectedAt" type="date" defaultValue={order?.expectedAt?.slice(0, 10) ?? ""} className={`${inputClass} mt-1`} /></div></div>
    <fieldset><legend className="text-xs font-bold uppercase tracking-wider text-slate-500">Ingredients</legend><div className="mt-2 space-y-2">{lines.map((line, index) => { const unit = ingredients.find((ingredient) => ingredient.id === line.ingredientId)?.unit; return <div key={index} className="grid gap-2 rounded-lg border border-slate-100 bg-slate-50 p-3 sm:grid-cols-[1fr_130px_150px_auto] sm:items-center"><select aria-label={`Ingredient ${index + 1}`} value={line.ingredientId} onChange={(event) => chooseIngredient(index, event.target.value)} className={inputClass} required><option value="" disabled>Select ingredient</option>{ingredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name} ({ingredient.unit})</option>)}</select><input aria-label={`Quantity ${index + 1}`} value={line.quantity} onChange={(event) => updateLine(index, { quantity: event.target.value })} type="number" min="0.001" step="0.001" placeholder={`Qty${unit ? ` (${unit})` : ""}`} className={inputClass} required /><input aria-label={`Unit cost ${index + 1}`} value={line.unitCost} onChange={(event) => updateLine(index, { unitCost: event.target.value })} type="number" min="0" step="0.0001" placeholder="Unit cost" className={inputClass} required /><button type="button" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))} className="rounded-lg px-3 py-2 text-xs font-semibold text-rose-600 disabled:text-slate-300">Remove</button></div>; })}</div><button type="button" onClick={() => setLines((current) => [...current, { ingredientId: "", quantity: "", unitCost: "" }])} className="mt-2 text-xs font-bold text-emerald-700">+ Add ingredient</button></fieldset>
    <div><button disabled={pending || !suppliers.length || !ingredients.length} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-50">{pending ? "Saving…" : order ? "Save draft" : "Create draft"}</button><ActionFeedback state={state} /></div>
  </form>;
}

const badge: Record<PurchaseOrderStatusValue, string> = { DRAFT: "bg-slate-100 text-slate-600", ORDERED: "bg-blue-50 text-blue-700", PARTIALLY_RECEIVED: "bg-amber-50 text-amber-700", RECEIVED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-rose-50 text-rose-700" };
const transitions: Partial<Record<PurchaseOrderStatusValue, Array<{ to: PurchaseOrderStatusValue; label: string }>>> = { DRAFT: [{ to: "ORDERED", label: "Mark ordered" }, { to: "CANCELLED", label: "Cancel" }], ORDERED: [{ to: "PARTIALLY_RECEIVED", label: "Mark partially received" }, { to: "RECEIVED", label: "Receive all" }, { to: "CANCELLED", label: "Cancel" }], PARTIALLY_RECEIVED: [{ to: "RECEIVED", label: "Receive all" }] };
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "—"; }

function OrderCard({ order, suppliers, ingredients, currency }: { order: PurchaseOrderView; suppliers: SupplierOption[]; ingredients: IngredientOption[]; currency: string }) {
  const [transitionState, transitionAction, transitioning] = useActionState(transitionPurchaseOrderAction, initialState);
  const [deleteState, deleteAction, deleting] = useActionState(deletePurchaseOrderAction, initialState);
  return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{order.supplier.name}</h2><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${badge[order.status]}`}>{order.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-xl font-bold text-slate-950">{new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(order.totalAmount)}</p><p className="mt-1 text-xs text-slate-500">{order.items.length} {order.items.length === 1 ? "item" : "items"}</p></div><div className="grid grid-cols-3 gap-4 text-xs"><div><p className="text-slate-400">Ordered</p><p className="mt-1 font-semibold text-slate-700">{date(order.orderedAt)}</p></div><div><p className="text-slate-400">Expected</p><p className="mt-1 font-semibold text-slate-700">{date(order.expectedAt)}</p></div><div><p className="text-slate-400">Created</p><p className="mt-1 font-semibold text-slate-700">{date(order.createdAt)}</p></div></div></div>
    <details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-xs font-bold text-emerald-700">View {order.status === "DRAFT" ? "or edit " : ""}items</summary>{order.status === "DRAFT" ? <OrderForm order={order} suppliers={suppliers} ingredients={ingredients} /> : <ul className="mt-3 divide-y divide-slate-100">{order.items.map((item) => <li key={item.id} className="flex justify-between py-2 text-sm"><span className="text-slate-700">{item.ingredientName}</span><span className="text-slate-500">{item.quantity} {item.unit} × {item.unitCost}</span></li>)}</ul>}</details>
    <div className="mt-4 flex flex-wrap gap-2">{transitions[order.status]?.map((transition) => <form key={transition.to} action={transitionAction} onSubmit={(event) => { const consequential = transition.to === "RECEIVED" || transition.to === "CANCELLED"; if (consequential && !window.confirm(transition.to === "RECEIVED" ? "Receive this order and add all quantities to inventory?" : "Cancel this purchase order?")) event.preventDefault(); }}><input type="hidden" name="purchaseOrderId" value={order.id} /><input type="hidden" name="to" value={transition.to} /><button disabled={transitioning} className={`rounded-lg px-3 py-2 text-xs font-bold disabled:opacity-50 ${transition.to === "RECEIVED" ? "bg-emerald-700 text-white" : "border border-slate-200 text-slate-700 hover:bg-slate-50"}`}>{transition.label}</button></form>)}{order.status === "DRAFT" && <form action={deleteAction} onSubmit={(event) => { if (!window.confirm("Delete this draft purchase order?")) event.preventDefault(); }}><input type="hidden" name="purchaseOrderId" value={order.id} /><button disabled={deleting} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600 disabled:opacity-50">Delete draft</button></form>}</div><ActionFeedback state={transitionState} /><ActionFeedback state={deleteState} />
  </article>;
}

export function PurchaseOrderManager({ orders, suppliers, ingredients, currency, activeStatus }: { orders: PurchaseOrderView[]; suppliers: SupplierOption[]; ingredients: IngredientOption[]; currency: string; activeStatus?: PurchaseOrderStatusValue }) {
  const filters: Array<{ label: string; value?: PurchaseOrderStatusValue }> = [{ label: "All" }, { label: "Draft", value: "DRAFT" }, { label: "Ordered", value: "ORDERED" }, { label: "Partial", value: "PARTIALLY_RECEIVED" }, { label: "Received", value: "RECEIVED" }, { label: "Cancelled", value: "CANCELLED" }];
  return <><details className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-sm font-bold text-emerald-700">Create purchase order</summary>{!suppliers.length || !ingredients.length ? <p className="mt-4 text-sm text-amber-700">Add at least one supplier and ingredient before creating a purchase order.</p> : <OrderForm suppliers={suppliers} ingredients={ingredients} />}</details><nav aria-label="Purchase order filters" className="mt-5 flex flex-wrap gap-2">{filters.map((filter) => <Link key={filter.label} href={filter.value ? `/purchase-orders?status=${filter.value}` : "/purchase-orders"} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${activeStatus === filter.value ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{filter.label}</Link>)}</nav>{orders.length ? <div className="mt-4 space-y-4">{orders.map((order) => <OrderCard key={order.id} order={order} suppliers={suppliers} ingredients={ingredients} currency={currency} />)}</div> : <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h2 className="font-semibold text-slate-800">No purchase orders found</h2><p className="mt-1 text-sm text-slate-500">Create a draft or choose another status filter.</p></div>}</>;
}
