"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { ConfirmSubmitButton } from "@/components/ui/confirm-action";
import { ActionFeedback } from "@/components/catalog/action-feedback";
import type { CatalogActionState } from "@/lib/catalog/action-utils";
import { createOrderAction, transitionOrderAction } from "@/lib/orders/actions";
import { ORDER_STATUSES, ORDER_TYPES, type OrderStatusValue, type OrderTypeValue } from "@/lib/orders/policy";

type MenuOption = { id: string; name: string; category: string; price: number };
type OrderView = { id: string; orderNumber: string; status: OrderStatusValue; orderType: OrderTypeValue; subtotal: number; discount: number; tax: number; total: number; inventoryConsumedAt: string | null; createdAt: string; items: Array<{ id: string; menuItemId: string; menuItemName: string; quantity: number; unitPrice: number; totalPrice: number }> };
type Line = { menuItemId: string; quantity: string };
const initialState: CatalogActionState = { status: "idle" };
const inputClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/10";

function CreateOrderForm({ menuItems, currency }: { menuItems: MenuOption[]; currency: string }) {
  const [state, action, pending] = useActionState(createOrderAction, initialState);
  const [lines, setLines] = useState<Line[]>([{ menuItemId: "", quantity: "1" }]);
  const updateLine = (index: number, change: Partial<Line>) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...change } : line));
  const estimate = lines.reduce((sum, line) => sum + (menuItems.find((item) => item.id === line.menuItemId)?.price ?? 0) * (Number(line.quantity) || 0), 0);
  return <form action={action} className="mt-5 space-y-4"><input type="hidden" name="items" value={JSON.stringify(lines)} /><div className="grid gap-4 sm:grid-cols-3"><div><label className="text-xs font-semibold text-slate-600">Order type</label><select name="orderType" defaultValue="DINE_IN" className={`${inputClass} mt-1`}>{ORDER_TYPES.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></div><div><label className="text-xs font-semibold text-slate-600">Discount amount</label><input name="discount" type="number" min="0" step="0.01" defaultValue="0" className={`${inputClass} mt-1`} /></div><div><label className="text-xs font-semibold text-slate-600">Tax amount</label><input name="tax" type="number" min="0" step="0.01" defaultValue="0" className={`${inputClass} mt-1`} /></div></div><fieldset><legend className="text-xs font-bold uppercase tracking-wider text-slate-500">Order items</legend><div className="mt-2 space-y-2">{lines.map((line, index) => <div key={index} className="grid gap-2 rounded-lg border border-slate-100 bg-slate-50 p-3 sm:grid-cols-[1fr_130px_auto] sm:items-center"><select aria-label={`Menu item ${index + 1}`} value={line.menuItemId} onChange={(event) => updateLine(index, { menuItemId: event.target.value })} required className={inputClass}><option value="" disabled>Select active menu item</option>{menuItems.map((item) => <option key={item.id} value={item.id}>{item.name} · {new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(item.price)}</option>)}</select><input aria-label={`Quantity ${index + 1}`} value={line.quantity} onChange={(event) => updateLine(index, { quantity: event.target.value })} type="number" min="1" max="999" step="1" required className={inputClass} /><button type="button" disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))} className="rounded-lg px-3 py-2 text-xs font-semibold text-rose-600 disabled:text-slate-300">Remove</button></div>)}</div><button type="button" onClick={() => setLines((current) => [...current, { menuItemId: "", quantity: "1" }])} className="mt-2 text-xs font-bold text-emerald-700">+ Add menu item</button></fieldset><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">Estimated subtotal: <strong className="text-slate-800">{new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(estimate)}</strong> · final pricing is calculated server-side.</p><button disabled={pending || !menuItems.length} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-50">{pending ? "Creating…" : "Create order"}</button></div><ActionFeedback state={state} /></form>;
}

const badge: Record<OrderStatusValue, string> = { PENDING: "bg-slate-100 text-slate-600", CONFIRMED: "bg-blue-50 text-blue-700", PREPARING: "bg-amber-50 text-amber-700", READY: "bg-violet-50 text-violet-700", COMPLETED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-rose-50 text-rose-700" };
const nextStatus: Partial<Record<OrderStatusValue, { to: OrderStatusValue; label: string }>> = { PENDING: { to: "CONFIRMED", label: "Confirm" }, CONFIRMED: { to: "PREPARING", label: "Start preparing" }, PREPARING: { to: "READY", label: "Mark ready" }, READY: { to: "COMPLETED", label: "Complete" } };

function WorkflowControls({ order, compact = false }: { order: OrderView; compact?: boolean }) {
  const [state, action, pending] = useActionState(transitionOrderAction, initialState);
  const next = nextStatus[order.status];
  const cancellable = !["COMPLETED", "CANCELLED"].includes(order.status);
  return <div className={compact ? "mt-3" : "mt-4 border-t border-slate-100 pt-4"}><div className="flex flex-wrap gap-2">{next && <form action={action}><input type="hidden" name="orderId" value={order.id} /><input type="hidden" name="to" value={next.to} />{next.to === "PREPARING" ? <ConfirmSubmitButton pending={pending} label={next.label} confirmLabel="Start preparing" message="Start preparation and consume recipe inventory now?" className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-50" /> : <button disabled={pending} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{next.label}</button>}</form>}{cancellable && <form action={action}><input type="hidden" name="orderId" value={order.id} /><input type="hidden" name="to" value="CANCELLED" /><ConfirmSubmitButton pending={pending} label="Cancel" confirmLabel="Cancel order" message={order.inventoryConsumedAt ? "Cancel this order? Consumed inventory will not be restored." : "Cancel this order?"} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600 disabled:opacity-50" /></form>}</div><ActionFeedback state={state} /></div>;
}

function KitchenBoard({ orders }: { orders: OrderView[] }) {
  const columns: Array<{ status: OrderStatusValue; title: string }> = [{ status: "CONFIRMED", title: "Confirmed" }, { status: "PREPARING", title: "Preparing" }, { status: "READY", title: "Ready" }];
  return <section aria-labelledby="kitchen-heading" className="mt-7"><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-emerald-700">Live workflow</p><h2 id="kitchen-heading" className="mt-1 text-xl font-bold text-slate-950">Kitchen board</h2></div><p className="text-xs text-slate-500">{orders.length} active</p></div><div className="mt-4 grid gap-4 xl:grid-cols-3">{columns.map((column) => { const columnOrders = orders.filter((order) => order.status === column.status); return <section key={column.status} className="rounded-xl border border-slate-200 bg-slate-100/60 p-3"><h3 className="px-1 text-xs font-bold uppercase tracking-wider text-slate-500">{column.title} · {columnOrders.length}</h3><div className="mt-3 space-y-2">{columnOrders.length ? columnOrders.map((order) => <article key={order.id} className="rounded-lg border border-slate-200 bg-white p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-bold text-slate-900">{order.orderNumber}</p><p className="mt-0.5 text-xs text-slate-500">{order.items.reduce((sum, item) => sum + item.quantity, 0)} items · {order.orderType.replaceAll("_", " ")}</p></div><time className="text-xs text-slate-400">{new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(new Date(order.createdAt))}</time></div><WorkflowControls order={order} compact /></article>) : <p className="rounded-lg border border-dashed border-slate-200 bg-white p-5 text-center text-xs text-slate-400">No orders</p>}</div></section>; })}</div></section>;
}

function OrderCard({ order, currency }: { order: OrderView; currency: string }) {
  const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(value);
  return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{order.orderNumber}</h2><span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${badge[order.status]}`}>{order.status}</span><span className="rounded-full bg-slate-50 px-2 py-0.5 text-[11px] font-semibold text-slate-500">{order.orderType.replaceAll("_", " ")}</span></div><time className="mt-1 block text-xs text-slate-400">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.createdAt))}</time></div><p className="text-xl font-bold text-slate-950">{money(order.total)}</p></div><ul className="mt-4 divide-y divide-slate-100 border-y border-slate-100">{order.items.map((item) => <li key={item.id} className="flex justify-between gap-4 py-2.5 text-sm"><span className="text-slate-700">{item.quantity} × {item.menuItemName}</span><span className="font-medium text-slate-600">{money(item.totalPrice)}</span></li>)}</ul><dl className="mt-3 grid grid-cols-4 gap-3 text-xs"><div><dt className="text-slate-400">Subtotal</dt><dd className="mt-1 font-semibold text-slate-700">{money(order.subtotal)}</dd></div><div><dt className="text-slate-400">Discount</dt><dd className="mt-1 font-semibold text-slate-700">{money(order.discount)}</dd></div><div><dt className="text-slate-400">Tax</dt><dd className="mt-1 font-semibold text-slate-700">{money(order.tax)}</dd></div><div><dt className="text-slate-400">Total</dt><dd className="mt-1 font-bold text-slate-900">{money(order.total)}</dd></div></dl>{order.inventoryConsumedAt && <p className="mt-3 text-xs text-slate-500">Recipe inventory consumed when preparation began.</p>}<WorkflowControls order={order} /></article>;
}

export function OrderManager({ orders, kitchenOrders, menuItems, currency, activeStatus, activeType }: { orders: OrderView[]; kitchenOrders: OrderView[]; menuItems: MenuOption[]; currency: string; activeStatus?: OrderStatusValue; activeType?: OrderTypeValue }) {
  const href = (status?: OrderStatusValue, type?: OrderTypeValue) => { const params = new URLSearchParams(); if (status) params.set("status", status); if (type) params.set("type", type); return params.size ? `/orders?${params}` : "/orders"; };
  return <><details className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-sm font-bold text-emerald-700">Create order</summary>{menuItems.length ? <CreateOrderForm menuItems={menuItems} currency={currency} /> : <p className="mt-4 text-sm text-amber-700">Add an active menu item before creating an order.</p>}</details><KitchenBoard orders={kitchenOrders} /><section aria-labelledby="all-orders-heading" className="mt-8"><h2 id="all-orders-heading" className="text-xl font-bold text-slate-950">All orders</h2><div className="mt-4 flex flex-wrap gap-2"><Link href={href(undefined, activeType)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${!activeStatus ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>All statuses</Link>{ORDER_STATUSES.map((status) => <Link key={status} href={href(status, activeType)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${activeStatus === status ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{status.replaceAll("_", " ")}</Link>)}</div><div className="mt-2 flex flex-wrap gap-2"><Link href={href(activeStatus)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${!activeType ? "bg-emerald-700 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>All types</Link>{ORDER_TYPES.map((type) => <Link key={type} href={href(activeStatus, type)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${activeType === type ? "bg-emerald-700 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{type.replaceAll("_", " ")}</Link>)}</div>{orders.length ? <div className="mt-4 space-y-4">{orders.map((order) => <OrderCard key={order.id} order={order} currency={currency} />)}</div> : <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h3 className="font-semibold text-slate-800">No orders found</h3><p className="mt-1 text-sm text-slate-500">Create an order or choose another filter.</p></div>}</section></>;
}
