ALTER TYPE "AIActionProposalType" ADD VALUE IF NOT EXISTS 'CREATE_ORDER';
ALTER TYPE "AIActionProposalType" ADD VALUE IF NOT EXISTS 'UPDATE_ORDER_ITEMS';
ALTER TYPE "AIActionProposalType" ADD VALUE IF NOT EXISTS 'TRANSITION_ORDER_STATUS';
