import assert from "node:assert/strict";
import test from "node:test";
import { validateInventoryProposalIntent, validateInventoryProposalTool, INVENTORY_PROPOSAL_TOOL } from "@/lib/ai/inventory-proposal-tool";
import { getAIActionRegistration, getRegisteredAIActionTypes } from "@/lib/ai/action-registry";
import { validateAIApprovalRequest } from "@/lib/ai/action-request";
import { calculateStockAdjustment, convertToBaseUnit, normalizeQuantityUnit } from "@/lib/inventory/units";
import { getReadOnlyToolContractNames, validateReadOnlyToolArguments } from "@/lib/ai/tool-contracts";
import { InventoryMovementType, Prisma } from "@/generated/prisma/client";
import { applyInventoryDeltaInTransaction } from "@/lib/services/inventory-movements";

const restaurant = { id: "trusted", name: "Kitchen", timezone: "Asia/Kolkata", currency: "INR", guestCapacity: 100 };

test("inventory actions are medium-risk admin-approved proposals", () => { for (const type of ["CREATE_INGREDIENT", "UPDATE_INGREDIENT", "ADJUST_INVENTORY_STOCK"] as const) { const registration = getAIActionRegistration(type); assert.equal(registration?.handlerKey, "inventory"); assert.equal(registration?.policy.riskLevel, "MEDIUM"); assert.equal(registration?.policy.authorization, "ORGANIZATION_ADMIN"); assert.equal(registration?.policy.humanApprovalRequired, true); } assert.equal(getRegisteredAIActionTypes().includes("DELETE_INGREDIENT" as never), false); });
test("create and metadata update proposals use strict bounded fields", () => { const created = validateInventoryProposalTool({ action_type: "CREATE_INGREDIENT", ingredient_name: "Basmati Rice", unit: "kg", initial_stock: 20, reorder_level: 5, cost_per_unit: 80, explanation: "Requested" }); assert.equal(created.initialStock, 20); const updated = validateInventoryProposalTool({ action_type: "UPDATE_INGREDIENT", ingredient_name: "Paneer", reorder_level: 10, explanation: "Update threshold" }); assert.equal(updated.reorderLevel, 10); assert.throws(() => validateInventoryProposalTool({ action_type: "DELETE_INGREDIENT", ingredient_name: "Paneer", explanation: "Delete" })); assert.throws(() => validateInventoryProposalTool({ action_type: "UPDATE_INGREDIENT", ingredient_name: "Paneer", currentStock: 99, explanation: "Tamper" })); });
test("receipt, usage, waste, and count intents remain explicit", () => { assert.equal(validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Onion", adjustment_kind: "RECEIPT", quantity: 15, quantity_unit: "kg", explanation: "Delivery" }).adjustmentKind, "RECEIPT"); assert.equal(validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Paneer", adjustment_kind: "USAGE", quantity: 2, quantity_unit: "kg", explanation: "Staff meal" }).adjustmentKind, "USAGE"); assert.equal(validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Tomato", adjustment_kind: "WASTE", quantity: 3, quantity_unit: "kg", explanation: "Spoilage" }).adjustmentKind, "WASTE"); assert.equal(validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Rice", adjustment_kind: "COUNT", counted_stock: 18, quantity_unit: "kg", explanation: "Physical count" }).countedStock, 18); });
test("stock proposals use the user's explicit measurement and tolerate bounded unit typos", () => { const kg = validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Paneer", adjustment_kind: "COUNT", counted_stock: 5, quantity_unit: "kg", explanation: "Count" }); assert.deepEqual({ unit: validateInventoryProposalIntent(kg, "Set Paneer stock to 10 kg").quantityUnit, count: validateInventoryProposalIntent(kg, "Set Paneer stock to 10 kg").countedStock }, { unit: "kg", count: 10 }); assert.deepEqual({ unit: validateInventoryProposalIntent(kg, "Set Paneer stock to 5000g").quantityUnit, count: validateInventoryProposalIntent(kg, "Set Paneer stock to 5000g").countedStock }, { unit: "g", count: 5000 }); assert.deepEqual({ unit: validateInventoryProposalIntent(kg, "Set Paneer stock to 8kh").quantityUnit, count: validateInventoryProposalIntent(kg, "Set Paneer stock to 8kh").countedStock }, { unit: "kg", count: 8 }); assert.equal(validateInventoryProposalIntent(kg, "Set Paneer stock to 10 pieces").quantityUnit, "piece"); const missing = validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Paneer", adjustment_kind: "COUNT", counted_stock: 5, explanation: "Count" }); assert.deepEqual({ unit: validateInventoryProposalIntent(missing, "Set Paneer stock to 5,000 g").quantityUnit, count: validateInventoryProposalIntent(missing, "Set Paneer stock to 5,000 g").countedStock }, { unit: "g", count: 5000 }); assert.throws(() => validateInventoryProposalIntent(missing, "Set Paneer stock to ten"), /explicit quantity unit/i); });

test("delta adjustments also use the original explicit amount before conversion", () => { const receipt = validateInventoryProposalTool({ action_type: "ADJUST_INVENTORY_STOCK", ingredient_name: "Milk", adjustment_kind: "RECEIPT", quantity: 5, quantity_unit: "litre", explanation: "Receipt" }); const validated = validateInventoryProposalIntent(receipt, "We received 5000ml Milk"); assert.equal(validated.quantity, 5000); assert.equal(validated.quantityUnit, "ml"); });
test("unit conversion permits only deterministic compatible conversions", () => { assert.equal(convertToBaseUnit(500, "g", "kg"), 0.5); assert.equal(convertToBaseUnit(750, "ml", "litre"), 0.75); assert.equal(convertToBaseUnit(2, "pieces", "piece"), 2); assert.equal(convertToBaseUnit(1, "piece", "kg"), null); assert.equal(normalizeQuantityUnit("Liters"), "litre"); });
test("server-owned stock arithmetic prevents negative inventory", () => { assert.deepEqual(calculateStockAdjustment({ currentStock: 12, kind: "RECEIPT", quantity: 20 }), { delta: 20, stockAfter: 32 }); assert.deepEqual(calculateStockAdjustment({ currentStock: 15, kind: "WASTE", quantity: 3 }), { delta: -3, stockAfter: 12 }); assert.deepEqual(calculateStockAdjustment({ currentStock: 25, kind: "COUNT", countedStock: 21 }), { delta: -4, stockAfter: 21 }); assert.equal(calculateStockAdjustment({ currentStock: 1, kind: "USAGE", quantity: 2 }), null); });
test("inventory read tools reject browser tenant injection", () => { const names = getReadOnlyToolContractNames(); for (const name of ["find_ingredients", "get_ingredient_details", "list_recent_inventory_movements"]) assert.ok(names.includes(name as never)); assert.deepEqual(validateReadOnlyToolArguments("find_ingredients", { name: "paneer" }, restaurant), { name: "paneer" }); assert.throws(() => validateReadOnlyToolArguments("find_ingredients", { name: "paneer", restaurantId: "other" }, restaurant)); assert.equal(names.includes(INVENTORY_PROPOSAL_TOOL as never), false); });
test("browser approval cannot tamper with inventory resource or action type", () => { assert.ok(validateAIApprovalRequest({ proposalId: "proposal-1" })); assert.equal(validateAIApprovalRequest({ proposalId: "proposal-1", ingredientId: "other" }), null); assert.equal(validateAIApprovalRequest({ proposalId: "proposal-1", actionType: "ADJUST_INVENTORY_STOCK" }), null); });
test("stock mutation and movement use the same transaction port", async () => { let stock = new Prisma.Decimal(10); let movements = 0; const transaction = { ingredient: { findFirst: async () => ({ id: "ingredient-1", currentStock: stock }), updateMany: async ({ data }: { data: { currentStock: Prisma.Decimal } }) => { stock = data.currentStock; return { count: 1 }; } }, inventoryMovement: { create: async () => { movements += 1; return { id: "movement-1" }; } } }; const result = await applyInventoryDeltaInTransaction(transaction as never, { restaurantId: "restaurant-1", ingredientId: "ingredient-1", delta: 5, type: InventoryMovementType.RECEIPT }); assert.equal(result.stockAfter, 15); assert.equal(stock.toNumber(), 15); assert.equal(movements, 1); });
test("a concurrent stock claim failure creates no movement", async () => { let movements = 0; const transaction = { ingredient: { findFirst: async () => ({ id: "ingredient-1", currentStock: new Prisma.Decimal(10) }), updateMany: async () => ({ count: 0 }) }, inventoryMovement: { create: async () => { movements += 1; return { id: "movement-1" }; } } }; await assert.rejects(() => applyInventoryDeltaInTransaction(transaction as never, { restaurantId: "restaurant-1", ingredientId: "ingredient-1", delta: -2, type: InventoryMovementType.USAGE }), /changed/i); assert.equal(movements, 0); });
