import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import Link from "next/link";
import { Icon, type IconName } from "@/components/icons";
import { PricingCard } from "@/components/marketing/pricing-card";
import { PublicNavigation } from "@/components/marketing/public-navigation";

export const metadata: Metadata = {
  title: "RestroPilot AI — Restaurant Operations OS",
  description: "Manage restaurant operations, inventory, purchasing, reservations, sales analytics and AI-assisted decision support from one workspace.",
  openGraph: { title: "RestroPilot AI — Restaurant Operations OS", description: "One intelligent operations workspace for restaurant owners and operators.", type: "website" },
};

const features: { icon: IconName; title: string; copy: string }[] = [
  { icon: "orders", title: "Orders & kitchen", copy: "Move internal orders through a clear kitchen workflow with recipe-based inventory control." },
  { icon: "menu", title: "Menu & recipes", copy: "Manage dishes, pricing, availability, and the ingredients each item consumes." },
  { icon: "inventory", title: "Inventory & procurement", copy: "Track stock, suppliers, purchase orders, receiving, and low-stock attention items." },
  { icon: "reservations", title: "Reservations", copy: "Organize upcoming bookings, guest counts, status, and operational capacity." },
  { icon: "sales", title: "Sales analytics", copy: "Understand revenue, order mix, top sellers, daily trends, and peak service hours." },
  { icon: "sparkles", title: "Controlled AI Manager", copy: "Ask questions grounded in approved restaurant data, with human approval before draft actions." },
];

export default async function PublicHome() {
  const { isAuthenticated } = await auth();
  const primaryHref = isAuthenticated ? "/overview" : "/sign-up";
  return <div className="marketing-page min-h-screen overflow-x-hidden bg-white text-slate-950">
    <PublicNavigation signedIn={isAuthenticated} />
    <main>
      <section className="relative isolate px-5 pb-20 pt-18 sm:px-8 sm:pb-28 sm:pt-24"><div className="marketing-glow" aria-hidden /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-4xl text-center"><p className="inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-xs font-bold uppercase tracking-[0.14em] text-emerald-800">AI-powered restaurant operations</p><h1 className="mt-7 text-balance text-4xl font-bold tracking-[-0.045em] text-slate-950 sm:text-6xl lg:text-7xl">Run your restaurant with clarity.</h1><p className="mx-auto mt-6 max-w-2xl text-pretty text-lg leading-8 text-slate-600">One operations system for daily service, inventory, purchasing, reservations, performance, and AI-assisted decisions grounded in your own restaurant data.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href={primaryHref} className="rounded-xl bg-emerald-700 px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-emerald-900/10 hover:bg-emerald-800">{isAuthenticated ? "Open dashboard" : "Get started"}</Link><Link href={isAuthenticated ? "/overview" : "/sign-in"} className="rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 hover:bg-slate-50">{isAuthenticated ? "View operations" : "Sign in"}</Link></div></div>
      <div id="product" className="relative mx-auto mt-16 max-w-6xl scroll-mt-24 rounded-[2rem] border border-slate-200 bg-slate-950 p-3 shadow-[0_32px_100px_rgba(15,23,42,0.2)] sm:p-5"><div className="rounded-[1.4rem] bg-slate-50 p-4 sm:p-7"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-700 text-white"><Icon name="sparkles" className="h-5 w-5" /></span><div><p className="text-sm font-bold text-slate-900">Operations briefing</p><p className="text-xs text-slate-500">Today · Restaurant-local time</p></div></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Live workspace</span></div><div className="mt-5 grid gap-4 md:grid-cols-4">{[["Revenue", "₹84,200", "+8.4%"],["Orders", "174", "Today"],["Reservations", "42", "Tonight"],["Inventory", "3 alerts", "Review"]].map(([label,value,note]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-slate-950">{value}</p><p className="mt-1 text-xs font-semibold text-emerald-700">{note}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-bold text-slate-900">Recent performance</p><div className="mt-6 flex h-32 items-end gap-3" aria-hidden>{[38,55,46,72,62,88,78].map((height,index) => <span key={index} className="flex-1 rounded-t-md bg-emerald-600/90" style={{ height: `${height}%` }} />)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-bold text-slate-900">Needs attention</p><div className="mt-4 space-y-3">{["Low-stock ingredients", "Friday reservation demand", "Open purchase orders"].map((item) => <div key={item} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm font-semibold text-slate-700"><span className="h-2 w-2 rounded-full bg-amber-500" />{item}</div>)}</div></div></div></div></div></div></section>

      <section className="border-y border-slate-200 bg-slate-50 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">AI Manager</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">Ask your restaurant, not a generic chatbot.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">RestroPilot uses approved, tenant-scoped tools for restaurant facts. Analysis is read-only by default, and purchase-order recommendations require explicit human approval before a draft is created.</p><div className="mt-7 flex flex-wrap gap-2">{["Restaurant-specific answers", "Approved data only", "Human approval required"].map((item) => <span key={item} className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700">{item}</span>)}</div></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-xl shadow-slate-900/5"><div className="rounded-xl bg-slate-950 p-4 text-sm text-white">What needs my attention today?</div><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Operational briefing</p><ul className="mt-3 space-y-3 text-sm leading-6 text-slate-700"><li>• Review ingredients at or below their reorder level.</li><li>• Check upcoming reservation demand before service.</li><li>• Review open purchase orders before creating another draft.</li></ul></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{["Which ingredients are running low?", "How much revenue did we make yesterday?", "How busy is Friday looking?", "Do we have open purchase orders?"].map((item) => <div key={item} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600">{item}</div>)}</div></div></div></section>

      <section id="how-it-works" className="scroll-mt-24 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">How it works</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">From restaurant data to daily decisions.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["01","Connect your operations","Add or import menu, inventory, orders, suppliers, reservations, and purchasing data."],["02","Run everything together","Manage daily restaurant workflows from one organization-scoped workspace."],["03","Ask RestroPilot AI","Get grounded analysis and controlled recommendations based on approved operational data."]].map(([number,title,copy]) => <article key={number} className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-emerald-700">{number}</p><h3 className="mt-8 text-xl font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

      <section id="features" className="scroll-mt-24 bg-slate-950 px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-400">Built for operations</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">The working parts of your restaurant, in one place.</h2><p className="mt-5 text-base leading-7 text-slate-300">Conventional operations remain dependable. AI adds decision support without bypassing your controls.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature) => <article key={feature.title} className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/15 text-emerald-300"><Icon name={feature.icon} className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-bold">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{feature.copy}</p></article>)}</div><p className="mt-8 text-sm text-slate-400">Also included: data import, restaurant settings, workspace switching, and a live operational attention center.</p></div></section>

      <section id="pricing" className="scroll-mt-24 bg-slate-50 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Prototype pricing</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">One complete operations workspace.</h2><p className="mt-5 text-base leading-7 text-slate-600">Choose a display duration. Billing and checkout are not enabled in this prototype.</p></div><div className="mt-12"><PricingCard signedIn={isAuthenticated} /></div></div></section>

      <section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl overflow-hidden rounded-[2rem] bg-emerald-800 px-6 py-14 text-center text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.15em] text-emerald-200">Restaurant data, made actionable</p><h2 className="mx-auto mt-4 max-w-3xl text-3xl font-bold tracking-tight sm:text-5xl">Your restaurant already creates the data. RestroPilot helps you act on it.</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={primaryHref} className="rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-emerald-900">{isAuthenticated ? "Open dashboard" : "Get started"}</Link><Link href={isAuthenticated ? "/overview" : "/sign-in"} className="rounded-xl border border-white/30 px-6 py-3.5 text-sm font-bold text-white">{isAuthenticated ? "View operations" : "Sign in"}</Link></div></div></section>
    </main>
    <footer className="border-t border-slate-200 px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><Link href="/" className="font-bold text-slate-950">RestroPilot AI <span className="font-medium text-slate-400">· Operations OS</span></Link><nav aria-label="Footer navigation" className="flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-slate-600"><a href="#product">Product</a><a href="#features">Features</a><a href="#pricing">Pricing</a><Link href={isAuthenticated ? "/overview" : "/sign-in"}>{isAuthenticated ? "Dashboard" : "Sign in"}</Link>{!isAuthenticated && <Link href="/sign-up">Get started</Link>}</nav></div></footer>
  </div>;
}
