import { AIManagerError } from "@/lib/ai/errors";
import type { OrderActionType, OrderProposalCandidate } from "@/lib/ai/action-proposal-types";
import type { AIToolDefinition } from "@/lib/ai/types";
import { ORDER_STATUSES, ORDER_TYPES } from "@/lib/orders/policy";

export const ORDER_PROPOSAL_TOOL = "propose_order_action";
const actionTypes: OrderActionType[] = ["CREATE_ORDER", "UPDATE_ORDER_ITEMS", "TRANSITION_ORDER_STATUS"];
export const orderProposalToolDefinition: AIToolDefinition = { name: ORDER_PROPOSAL_TOOL, description: "Propose, but never execute, creating an order, replacing the items of an unprepared order, or transitioning an order status. Resolve exact menu names and order numbers with read tools first. Prices are always server-resolved and human approval is required.", parameters: { type: "object", properties: { action_type: { type: "string", enum: actionTypes }, order_number: { type: "string", maxLength: 80 }, order_type: { type: "string", enum: ORDER_TYPES }, items: { type: "array", minItems: 1, maxItems: 30, items: { type: "object", properties: { menu_item_name: { type: "string", minLength: 1, maxLength: 120 }, quantity: { type: "integer", minimum: 1, maximum: 999 } }, required: ["menu_item_name", "quantity"], additionalProperties: false } }, discount: { type: "number", minimum: 0 }, tax: { type: "number", minimum: 0 }, status: { type: "string", enum: ORDER_STATUSES }, explanation: { type: "string", minLength: 1, maxLength: 1000 } }, required: ["action_type", "explanation"], additionalProperties: false } };
function plain(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new AIManagerError("INVALID_TOOL", "Order proposal must be a plain object."); return value as Record<string, unknown>; }
export function validateOrderProposalTool(value: unknown): OrderProposalCandidate {
  const record = plain(value); const allowed = ["action_type", "order_number", "order_type", "items", "discount", "tax", "status", "explanation"];
  if (Object.keys(record).some((key) => !allowed.includes(key)) || !actionTypes.includes(record.action_type as OrderActionType)) throw new AIManagerError("INVALID_TOOL", "Order action is unsupported.");
  const text = (key: string, max = 1000) => { const v = record[key]; if (v === undefined) return undefined; if (typeof v !== "string" || !v.trim() || v.length > max) throw new AIManagerError("INVALID_TOOL", `${key} is invalid.`); return v.trim(); };
  const actionType = record.action_type as OrderActionType; const explanation = text("explanation")!; const orderNumber = text("order_number", 80);
  if ((actionType === "UPDATE_ORDER_ITEMS" || actionType === "TRANSITION_ORDER_STATUS") && !orderNumber) throw new AIManagerError("INVALID_TOOL", "An exact order number from a read tool is required.");
  if (record.order_type !== undefined && !ORDER_TYPES.includes(record.order_type as never)) throw new AIManagerError("INVALID_TOOL", "Order type is invalid.");
  if (record.status !== undefined && !ORDER_STATUSES.includes(record.status as never)) throw new AIManagerError("INVALID_TOOL", "Order status is invalid.");
  const items = record.items === undefined ? undefined : (() => { if (!Array.isArray(record.items) || !record.items.length || record.items.length > 30) throw new AIManagerError("INVALID_TOOL", "Order items are invalid."); return record.items.map((raw) => { const line = plain(raw); if (Object.keys(line).some((key) => !["menu_item_name", "quantity"].includes(key)) || typeof line.menu_item_name !== "string" || !line.menu_item_name.trim() || !Number.isSafeInteger(line.quantity) || Number(line.quantity) < 1 || Number(line.quantity) > 999) throw new AIManagerError("INVALID_TOOL", "An order line is invalid."); return { menuItemName: line.menu_item_name.trim(), quantity: Number(line.quantity) }; }); })();
  if ((actionType === "CREATE_ORDER" || actionType === "UPDATE_ORDER_ITEMS") && (!items || !record.order_type || !ORDER_TYPES.includes(record.order_type as never))) throw new AIManagerError("INVALID_TOOL", "Order items and type are required.");
  if (actionType === "TRANSITION_ORDER_STATUS" && !record.status) throw new AIManagerError("INVALID_TOOL", "Target status is required.");
  for (const key of ["discount", "tax"] as const) if (record[key] !== undefined && (typeof record[key] !== "number" || !Number.isFinite(record[key]) || record[key] < 0 || record[key] > 9_999_999.99)) throw new AIManagerError("INVALID_TOOL", `${key} is invalid.`);
  return { actionType, orderNumber, orderType: record.order_type as string | undefined, items, discount: record.discount as number | undefined, tax: record.tax as number | undefined, status: record.status as string | undefined, explanation };
}
